language: java

jdk:
  - oraclejdk8
  - oraclejdk11

script: 
  - env
  - mvn -B clean install sonar:sonar -Dsonar -Dsonar.projectKey=ops4j_org.ops4j.ramler

install: true

cache:
  directories:
  - $HOME/.m2

env:
  - secure: "E6XeMx8Du8gYI2AXRIaBxQ3VNP0n7lQIDAFr/6nLc9p63xqA2awZoLeakzKBCxJMIEy2fusC7QzX5JWsZdub3j5s8tdgUZSL5gSw9xRmRlWxNv2aehUS6g8qmctXB/Lpc32ND8YlT+8IUcqdoZJwlJYzoro18G3Mef8WsVZbk/NeOmghdzJxrmYMbb88e6oyxqrQL3GnyoYYGEVPIF3cJyt5AcEqFEErkAFFCYoK3U71aPklUCFKbEJglYMIYnraH9XOt8J7z0lu0XfHzL86ygm3wU8+yrLOd5Nct5Ra4kMnwTupOesbDmYjMHXpgCSXog8VJHeXd+9dE6TAFm37CvhoZ9QlUEbulyBnBUtBxvna8CeYK0K/uzqXxeVzysTW+WZ2HYIBrz4Fkwct4pfs9JJBUVfFvk28+KXakZXqasyTSuyczr3nOd+97gxdmNtRi/8CLvfUzwKwc6N45GbLijMXxBMAWM21F2o8eMkycpR2O9WPOfGVvnosDGCOegZCNriqeXv2znlzust9ebr6VLVJEGyq3ujq2KvKts85Rh7xbApq5+9Z9U5hBimkgQ/UVRAqBHGCpBmjTn2K4wFp/bz8+BUpaiHuI71kTtIFqwicNdtC8PsZh4qiCSwB3mIKAVKOsMwQQ+2SEYHngEZ3DvBn38xiUDO00JdQba9acMo="