language: java

jdk:
  - oraclejdk8
  - oraclejdk11

script: 
  - mvn -B clean install sonar:sonar -Dsonar.projectKey=ops4j_org.ops4j.ramler

install: true

cache:
  directories:
  - $HOME/.m2

addons:
  sonarcloud:
    organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
    token:
      secure: "LlJ0Tyu4jUbkLA1gzM/hb/2aLUdeGI0zVkbkamfei89zxpvbbTv2u5IpK2sB2ZTBGM1aHLJD+/7jr4zut5pXdDHQ2sGr8mOB1j63TNQOyjk2jk78cGLztZkAE3t8WI/e3+0+PXyp1vl7o7Wan18j/fgkBav8fz0pNwPHqeoic2NmPk10QuIYX0FFpcCPw8mJZFcIdwubgNRExkQGOyDvYriCvKX/vLgWTIqeRQHgnOiOWLc7u/EgKM9fXLmjU31Upf+2BrN1NavEyyhpaH5H1eKpL5OHbVgtQWa2XvZW7eGwfmMy/PpCoip1XQ+0sZ3I3P0r2qBP2w1Gk5sU0lLBPtt2a0BQJ89VJduSRiQUvLOcC5J3MmVyvEcKL8Dc3C5yLk1WRrxTtFBLgNXLd5ZDAOfcygwCtntDkaQPokUHuZrrAiY5dzYIRpI+UrJaRCRxpWWVEJZjuJfxhtdLLyhDqTqmt2oHJ8IhkpHO0lDtlr72i9tWSs/oCJMkJ7UMHDd25F73HAgH8H9gTAbTnjn9upI3mSO/DnQqlHA0VRrYxRwL/uLF4QrCWv/iW256DPqekyx58oP4jdr4mURpYtQ1LtaVbp1tq2/h44Be/88JcpvXLijvhfrIS4IVv7ou5oLWqr+jbzKU+Pkqn+nQ++HsOvvMOzm4VKlGbU7AEP3ghJA="
  